apiVersion: automation.cloudbees.io/v1alpha1
kind: Action
metadata:
  name: 'manual-approval-for-user'
  description: 'An action that requires manual approval from a specific user before continuing'
spec:
  inputs:
    approverEmail:
      description: 'The email address of the user who must approve the action'
      required: true
      default: 'ashok.alogicfocus@gmail.com'
    approvalMessage:
      description: 'The message displayed when waiting for approval'
      required: true
      default: 'Approval needed to proceed with the workflow.'
  outputs:
    approvalStatus:
      description: 'The status of the approval'
      value: 'pending'
  run:
    using: 'composite'
    steps:
      - name: 'request-approval'
        run: |
          echo "Requesting approval from ${{ inputs.approverEmail }}"
          echo "${{ inputs.approvalMessage }}"

          # Placeholder logic for integration with an approval service or system
          if [ "$APPROVED_BY" == "${{ inputs.approverEmail }}" ]; then
            echo "Approval granted by $APPROVED_BY"
            echo "::set-output name=approvalStatus::approved"
          else
            echo "Approval still pending or denied."
            echo "::set-output name=approvalStatus::pending"
          fi
        shell: bash
