name: 'Manual Approval for User'
description: 'An action that requires manual approval from a specific user before continuing'

inputs:
  approver_email:
    description: 'The email address of the user who must approve the action'
    required: true
    default: 'ashok.alogicfocus@gmail.com'
  approval_message:
    description: 'The message displayed when waiting for approval'
    required: true
    default: 'Approval needed to proceed with the workflow.'

outputs:
  approval_status:
    description: 'The status of the approval'
    value: 'pending'

runs:
  using: 'composite'
  steps:
    - run: |
        echo "Requesting approval from ${{ inputs.approver_email }}"
        echo "${{ inputs.approval_message }}"
        
        # Here you would include logic that integrates with a service or a custom solution
        # to send the approval request to the specific user.
        
        # This is a placeholder simulating approval logic.
        if [ "$APPROVED_BY" == "${{ inputs.approver_email }}" ]; then
          echo "Approval granted by $APPROVED_BY"
          echo "::set-output name=approval_status::approved"
        else
          echo "Approval still pending or denied."
          echo "::set-output name=approval_status::pending"
        fi
      shell: bash
